# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	#==============#
	# CentOS nodes #
	#==============#
	
	#Ansible-Node01
	config.vm.define "ansible-node01" do |cfg|
	   cfg.vm.box = "centos/7"
	   cfg.vm.provider "virtualbox" do |vb|
		 vb.name = "Ansible-Node01"
	   end
	   cfg.vm.host_name = "ansible-node01"
	   cfg.vm.network "public_network", ip: "192.168.1.11"
	   cfg.vm.network "forwarded_port", guest: 22, host: 60011, auto_correct: true, id: "ssh"
	   cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
	end
	
	#Ansible-Node02	 
	config.vm.define "ansible-node02" do |cfg|
	   cfg.vm.box = "centos/7"
	   cfg.vm.provider "virtualbox" do |vb|
		 vb.name = "Ansible-Node02"
	   end
	   cfg.vm.host_name = "ansible-node02"
	   cfg.vm.network "public_network", ip: "192.168.1.12"
	   cfg.vm.network "forwarded_port", guest: 22, host: 60012, auto_correct: true, id: "ssh"
	   cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	end
  
	#Ansible-Node03	 
	config.vm.define "ansible-node03" do |cfg|
	   cfg.vm.box = "centos/7"
	   cfg.vm.provider "virtualbox" do |vb|
		 vb.name = "Ansible-Node03"
	   end
	   cfg.vm.host_name = "ansible-node03"
	   cfg.vm.network "public_network", ip: "192.168.1.13"
	   cfg.vm.network "forwarded_port", guest: 22, host: 60013, auto_correct: true, id: "ssh"
	   cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
	end
  
    #==============#
    # Ubuntu nodes #
    #==============#
	
    #Ansible-Node04
    config.vm.define "ansible-node04" do |cfg|
       cfg.vm.box = "ubuntu/trusty64"
  	 cfg.vm.provider "virtualbox" do |vb|
  	   vb.name = "Ansible-Node04"
  	 end
  	 cfg.vm.host_name = "ansible-node04"
  	 cfg.vm.network "public_network", ip: "192.168.1.14"
  	 cfg.vm.network "forwarded_port", guest: 22, host: 60014, auto_correct: true, id: "ssh"
  	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    end
	
    #Ansible-Node05	 
    config.vm.define "ansible-node05" do |cfg|
       cfg.vm.box = "ubuntu/trusty64"
  	 cfg.vm.provider "virtualbox" do |vb|
  	   vb.name = "Ansible-Node05"
  	 end
  	 cfg.vm.host_name = "ansible-node05"
  	 cfg.vm.network "public_network", ip: "192.168.1.15"
  	 cfg.vm.network "forwarded_port", guest: 22, host: 60015, auto_correct: true, id: "ssh"
  	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    end
  
    #Ansible-Node06	 
    config.vm.define "ansible-node06" do |cfg|
       cfg.vm.box = "ubuntu/trusty64"
  	 cfg.vm.provider "virtualbox" do |vb|
  	   vb.name = "Ansible-Node06"
  	 end
  	 cfg.vm.host_name = "ansible-node06"
  	 cfg.vm.network "public_network", ip: "192.168.1.16"
  	 cfg.vm.network "forwarded_port", guest: 22, host: 60016, auto_correct: true, id: "ssh"
  	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    end
  
    #==============#
    # Windows node #
    #==============#
	
    #Ansible-win01
    config.vm.define "ansible-win01" do |cfg|
       cfg.vm.box = "sysnet4admin/windows2016"
  	 cfg.vm.provider "virtualbox" do |vb|
  	   vb.name = "Ansible-Node07"
  	   vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  	   vb.gui = false
  	 end
  	 cfg.vm.host_name = "ansible-node07"
  	 cfg.vm.network "public_network", ip: "192.168.1.17"
  	 cfg.vm.network "forwarded_port", guest: 22, host: 60017, auto_correct: true, id: "ssh"
  	 cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  	 cfg.vm.provision "shell", inline: "netsh advfirewall set allprofiles state off"
    end  
	
	#================#
	# Ansible Server #
	#================#
	
	config.vm.define "ansible-server" do |cfg|
	  cfg.vm.box = "centos/7"
	   cfg.vm.provider "virtualbox" do |vb|
		vb.name = "Ansible-Server"
	  end
	  cfg.vm.host_name = "ansible-server"
	  cfg.vm.network "public_network", ip: "192.168.1.10"
	  cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
	  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
	end
  end
