---
- hosts: centOS
  gather_facts: yes
  vars:
    user: anagent

  tasks:
  - name: backup existing Zabbix files
    shell: tar zcvf {{dest}} {{src}}
    vars:
      src: /zabbix/*
      dest: /zabbix/{{file_name}}
      file_name: backup_{{ansible_date_time.date}}.tar.gz

  - name: get list of old file in /zabbix
    shell: ls /zabbix
    register: list

  - name: remove old file in /zabbix
    shell: rm -rf {{src}}{{item}}
    with_list: "{{ list.stdout_lines }}"
    when: condi != item
    vars:
      condi: "{{ file_name }}"
      src: /zabbix/
      file_name: backup_{{ansible_date_time.date}}.tar.gz

  - name: upload zabiix install file
    include_tasks: set_upload_zabiix_file.yml
    vars:
      sys_info: 
        os: "{{ ansible_distribution }}"
        var: "{{ ansible_distribution_major_version }}"
        bit: "{{ ansible_architecture }}"
      src: "~/ansible/file/"
      dest: "/zabbix"

  - name: install zabbix
    include_tasks: set_install_zabbix.yml 

  - name: set zabbix conf
    include_tasks: set_zabbix_conf.yml
    vars:
      ip: 192.168.1.10
      log_path: /zabbix/log/zabbix_agentd.log

  - name: start zabbix
    include_tasks: set_start_zabbix.yml
