---
 - name: backup
   win_shell: Compress-Archive -Path C:\\'Program Files\'\zabbix\  -DestinationPath {{BACKUP_DEST}}{{BACKUP_NAME}} -Force
  
 - name: remove old zabbix dir
   win_file:
     path: "{{ ZABBIX_HOME }}"
     state: absent

 - name: install zabbix
   include: jb_install.yml
