---
- name: get exists dir
  raw: ls -l {{src}} | grep {{target}}
  register: ls_list
  ignore_errors: yes

- name: init is_dir
  set_fact:
    is_dir: False

- name: set is_dir
  set_fact:
    is_dir: True
  when: item.split(' ')[-1] == target
  with_list: "{{ ls_list.stdout_lines }}"

- name: make dir
  raw: "{{root_authority}} mkdir {{src}}{{target}}"
  when: not is_dir
  vars:
    root_authority: "{{ 'sudo' if sudo == True else '' }}"
