---
- name: start zabbix
  raw: sh /zabbix/sbin/start.sh

- name: get zabbix process
  raw: ps -ef | grep -v grep | grep zabbix_agentd | wc -l
  register: rs

- name: chk zabbix process
  debug:
    msg: "{{ msg_run if rs.stdout | int > 0 else msg_not_run }}"
  failed_when: "{{ false if rs.stdout | int > 0 else true }}"
  vars:
    msg_run: "Working Zabbix agent Process..."
    msg_not_run: "ERROR!!! Please Check Zabbix agent Process..."
