---
- name: get exists dir of /zabbix
  raw: ls -l / | grep zabbix
  register: ls_list

- name: init is_zabbix
  set_fact:
    is_zabbix: False

- name: set is_zabbix
  set_fact:
    is_zabbix: True
  when: item.split(' ')[-1] == 'zabbix'
  with_list: "{{ ls_list.stdout_lines }}"

- name: make dir of /zabbix
  raw: sudo mkdir /zabbix
  when: not is_zabbix

- name: chown dir of /zabbix
  raw: sudo chown '{{ansible_ssh_user}}':'{{ansible_ssh_user}}' /zabbix

- name: get state /zabbix
  raw: ls -l / | grep zabbix
  register: zabbix_dir_info

- name: debug dir of /zabbix
  debug: var=zabbix_dir_info.stdout_lines
