---
- name: get OS Info
  include: get_os_info.yml

- name: set_fact zabbix install file name
  set_fact:
    file_name: "{{ 'zabbix_agnets_centos'+os_info.ver+'' if os_info.bit == '64' else '_i386' }}.tar.gz"

- name: upload zabbix file
  include: set_upload_file.yml

- name: unarchive file
  raw: tar zxvf {{zabbix_home}}/{{file_name}} -C {{zabbix_home}}

- name: run install.sh for install zabbix
  include: set_install_zabbix.yml

- name: chk zabbix conf
  include: chk_zabbix_conf.yml

- name: start zabbix
  include: set_start_zabbix.yml
