---

# zabbix configure
zabbix_ip: '127.0.0.1'
zabbix_log_path: '/tmp/zabbix_agentd.log'
#zabbix_path: '/home'

# etc
zabbix_home: '/zabbix/'
src: '/home/vagrant/ansible/roles/zabbix/files/'
dest: "{{ zabbix_home }}"
